---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: test-argo
    repoURL: https://github.com/sklgromek/argo-sync-fail
    targetRevision: main
  syncPolicy:
    automated: {}
